kind: project
spec:
  source: git://github.com/elbamit/remote-workflow-example.git
  load_source_on_run: true
  desired_state: online
  conda: ''
  functions:
  - url: func.py
    name: func-a
    kind: job
    image: artifactory.iguazeng.com:10557/amite/mlrun/mlrun:ig4-auth5
    handler: func_A
  - url: func.py
    name: func-b
    kind: job
    image: artifactory.iguazeng.com:10557/amite/mlrun/mlrun:ig4-auth5
    handler: func_B
  - url: func.py
    name: func-c
    kind: job
    image: artifactory.iguazeng.com:10557/amite/mlrun/mlrun:ig4-auth5
    handler: func_C
  workflows:
  - path: workflow.py
    name: workflow-func
status:
  state: online
metadata:
  name: remote-workflow
  created: '2026-01-01T16:06:06.377000'
